#!/bin/bash
(
    head -n 5 prefixfree.js
    curl --data-urlencode 'js_code@prefixfree.js' \
         --data 'output_info=compiled_code' \
         https://closure-compiler.appspot.com/compile
) > prefixfree.min.js
